name: Reserialise2

# trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  robot_job:
    # if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      target-ontology: ./cl-edit.owl

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Robot reserialise
      run: |
        curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
        java -jar robot.jar convert --input ${{env.target-ontology}} -f ofn --output ${{env.target-ontology}}

    - name: Commit ontology
      run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ${{env.target-ontology}}
          git commit -m "Automatic robot serialisation after merge of branch ${{github.event.pull_request.head.ref}}" || echo "No changes to commit"
          git push || echo "No changes to push"
