name: Reserialise

# trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge_job:
    # if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.26

    steps:
    - uses: actions/checkout@v2
    - name: robot reserialise
      run: |
        robot convert --input ./cl-full.owl -f ofn --output ./cl-full.owl
    - name: Commit ontology
      run: |
          git config --local user.name "serialiser_bot"
          git add ./cl-full.owl
          git commit -m "Automatic robot serialisation after merge"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        force: true