name: Reserialise2

# trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    # if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Robot reserialise
      run: |
        curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
        java -jar robot.jar convert --input ./cl-full.owl -f ofn --output ./cl-full.owl

    - name: Commit ontology
      run: |
          echo $GITHUB_WORKSPACE && pwd && echo ${{github.ref}} && ls
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ./cl-full.owl
          git commit -m "Automatic robot serialisation after merge of branch ${{github.event.pull_request.head.ref}}" -a
          git push
